### ISSUE TITLE
[BUG] faild to publish datasets after upload

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#2990] opened 2024-02-26 15:20 UTC
### Bug Description

whne uploading data the user usually choses to publish it. In some instances (not all so hard to reproduce) the publishing fails with a very criptical error message like in the screenshot

### Bug Reproduction

publish an uplaoded dataset

### Bug Screenshots

![MicrosoftTeams-image](https://github.com/UNDP-Data/geohub/assets/92793531/9ea2fdf5-5a78-4339-bbd4-f24dafd2d489)

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1309989872) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment] 2024-02-26 15:48
@iferencik which one are you using prod or dev? Looks like this is the same issue which I fixed in https://github.com/UNDP-Data/geohub/pull/2985 (it is not deployed to prod yet).

Please also provide required information to reproduce (for example, share the uploaded dataset, which properties have you selected in edit page, what is URL for the website, etc...)

**Closed** 2024-02-28 08:53 UTC
Labels: bug
